name: Standard Build and Update GitOps
on:
  workflow_call:
    inputs:
      app_name:
        required: true
        type: string
    secrets:
      GITOPS_BOT_TOKEN:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::092568126647:role/GitHubActionsDeployRole
          aws-region: eu-central-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
          
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ inputs.app_name }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

      - name: Update GitOps Repository
        run: |
          git clone https://x-access-token:${{ secrets.GITOPS_BOT_TOKEN }}@github.com/App-of-apps-argo-example/gitops-core.git
          cd gitops-core
          
          sed -i "s|repository: .*|repository: ${{ steps.login-ecr.outputs.registry }}/${{ inputs.app_name }}|" environments/stage/${{ inputs.app_name }}-values.yaml
          sed -i "s|tag: .*|tag: ${{ github.sha }}|" environments/stage/${{ inputs.app_name }}-values.yaml
          
          git config user.name "ci-bot"
          git config user.email "ci-bot@app-of-apps.com"
          git add .
          git commit -m "chore: deploy ${{ inputs.app_name }} version ${{ github.sha }}"
          git push
